# Copyright 2023 Intel Corporation. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# DESCRIPTION #
# ----------- #
# Use this launch file to launch 2 devices.
# The Parameters available for definition in the command line for each camera are described in rs_launch.configurable_parameters
# For each device, the parameter name was changed to include an index.
# For example: to set camera_name for device1 set parameter camera_name1.
# command line example:
# ros2 launch realsense2_camera rs_multi_camera_launch.py camera_name1:=D400 device_type2:=l5. device_type1:=d4..

"""Launch realsense2_camera node."""
import copy
from launch import LaunchDescription, LaunchContext
import launch_ros.actions
from launch.actions import IncludeLaunchDescription, OpaqueFunction, LogInfo
from launch.substitutions import LaunchConfiguration, ThisLaunchFileDir
from launch.launch_description_sources import PythonLaunchDescriptionSource
import sys
import os
import yaml
import pathlib
sys.path.append(str(pathlib.Path(__file__).parent.absolute()))
import rs_launch

local_parameters = [{'name': 'camera_name1', 'default': 'back', 'description': 'camera1 unique name'},
                    {'name': 'camera_name2', 'default': 'left', 'description': 'camera2 unique name'},
                    {'name': 'camera_namespace1', 'default': 'back', 'description': 'camera1 namespace'},
                    {'name': 'camera_namespace2', 'default': 'left', 'description': 'camera2 namespace'},
                    {'name': 'serial_no1', 'default': '_419122270813', 'description': 'camera1 serial number'},
                    {'name': 'serial_no2', 'default': '_218622276534', 'description': 'camera2 serial number'},
                    {'name': 'camera_name3', 'default': 'right', 'description': 'camera3 unique name'},
                    {'name': 'camera_namespace3', 'default': 'right', 'description': 'camera3 namespace'},
                    {'name': 'serial_no3', 'default': '_218622276687', 'description': 'camera3 serial number'},
                    {'name': 'camera_name4', 'default': 'front', 'description': 'camera4 unique name'},
                    {'name': 'camera_namespace4', 'default': 'front', 'description': 'camera4 namespace'},
                    {'name': 'serial_no4', 'default': '_313522070126', 'description': 'camera4 serial number'},
                    ]

def yaml_to_dict(path_to_yaml):
    with open(path_to_yaml, "r") as f:
        return yaml.load(f, Loader=yaml.SafeLoader)
    
def set_configurable_parameters(local_params):
    return dict([(param['original_name'], LaunchConfiguration(param['name'])) for param in local_params])

def duplicate_params(general_params, posix):
    local_params = copy.deepcopy(general_params)
    for param in local_params:
        param['original_name'] = param['name']
        param['name'] += posix
        if param['original_name'] == 'enable_depth':
            param['default'] = 'true'
        elif param['original_name'] == 'depth_module.depth_profile':
            param['default'] = '640,360,30'
        elif param['original_name'] == 'depth_module.color_profile':
            param['default'] = '640,360,30'
        elif param['original_name'] == 'rgb_camera.color_profile':
            param['default'] = '640,360,30'
        elif param['original_name'] == 'initial_reset':
            param['default'] = 'false'
        elif param['original_name'] == 'enable_color':
            param['default'] = 'true'
        elif param['original_name'] == 'enable_infra':
            param['default'] = 'false'
        elif param['original_name'] == 'enable_infra1':
            param['default'] = 'false'
        elif param['original_name'] == 'enable_infra2':
            param['default'] = 'false'
        elif param['original_name'] == 'enable_gyro':
            param['default'] = 'false'
        elif param['original_name'] == 'enable_accel':
            param['default'] = 'false'
    return local_params

def launch_static_transform_publisher_node(context : LaunchContext):
    # Load lifecycle nodes setting from YAML dynamically generated by CMAKE instead of environment variable
    lifecycle_param_file = os.path.join(
        os.path.dirname(__file__), '..', 'config', 'global_settings.yaml'
    )
    lifecycle_params = yaml_to_dict(lifecycle_param_file)
    use_lifecycle_node = lifecycle_params.get("use_lifecycle_node", False)

    node_action = launch_ros.actions.LifecycleNode if use_lifecycle_node else launch_ros.actions.Node
    log_message = "Launching as LifecycleNode" if use_lifecycle_node else "Launching as Normal ROS Node"
    
    # dummy static transformation from camera1 to camera2
    node2 = node_action(
        namespace="",
        name="tf2_static_transform_publisher_back",
        package = "tf2_ros",
        executable = "static_transform_publisher",
        arguments=[
            '0.0', '-0.125', '0.30', '-1.571', '0.7854', '-1.571',
            'base_footprint',
            context.launch_configurations['camera_name1'] + '_link'
        ]
    )
    node3 = node_action(
        namespace="",
        name="tf2_static_transform_publisher_left",
        package = "tf2_ros",
        executable = "static_transform_publisher",
        arguments=[
            '-0.125', '0.0', '0.30', '-3.142', '0.7854', '-1.571',
            'base_footprint',
            context.launch_configurations['camera_name2'] + '_link'
        ]
    )
    node4 = node_action(
        namespace="",
        name="tf2_static_transform_publisher_right",
        package = "tf2_ros",
        executable = "static_transform_publisher",
        arguments=[
            '0.125', '0.0', '0.30', '0.0', '0.7854', '-1.571',
            'base_footprint',
            context.launch_configurations['camera_name3'] + '_link'
        ]
    )
    # new front camera
    node5 = node_action(
        namespace="",
        name="tf2_static_transform_publisher_front",
        package = "tf2_ros",
        executable = "static_transform_publisher",
        arguments=[
            '0.0', '0.125', '0.176', '1.571', '0.5236', '-1.571',
            'base_footprint',
            context.launch_configurations['camera_name4'] + '_link'
        ]
    )
    return [LogInfo(msg=f"🚀 {log_message}"), node2, node3, node4, node5]

def generate_launch_description():
    params1 = duplicate_params(rs_launch.configurable_parameters, '1')
    params2 = duplicate_params(rs_launch.configurable_parameters, '2')
    params3 = duplicate_params(rs_launch.configurable_parameters, '3')
    params4 = duplicate_params(rs_launch.configurable_parameters, '4')
    return LaunchDescription(
        rs_launch.declare_configurable_parameters(local_parameters) +
        rs_launch.declare_configurable_parameters(params1) +
        rs_launch.declare_configurable_parameters(params2) +
        rs_launch.declare_configurable_parameters(params3) +
        rs_launch.declare_configurable_parameters(params4) +
        [
        OpaqueFunction(function=rs_launch.launch_setup,
                       kwargs = {'params'           : set_configurable_parameters(params1),
                                 'param_name_suffix': '1'}),
        OpaqueFunction(function=rs_launch.launch_setup,
                       kwargs = {'params'           : set_configurable_parameters(params2),
                                 'param_name_suffix': '2'}),
        OpaqueFunction(function=rs_launch.launch_setup,
                       kwargs = {'params'           : set_configurable_parameters(params3),
                                 'param_name_suffix': '3'}),
        OpaqueFunction(function=rs_launch.launch_setup,
                       kwargs = {'params'           : set_configurable_parameters(params4),
                                 'param_name_suffix': '4'}),
        OpaqueFunction(function=launch_static_transform_publisher_node)
    ])
